server:
  port: 8090
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogapp
    username: admin
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
