server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogapp
    username: dev
    password: dev_admin@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect